apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: grafana-pvc
    labels:
        name: grafana-pvc
spec:
    accessModes:
        -   ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
    name: graf-service
spec:
    selector:
        env: master
    type: NodePort
    ports:
        -   nodePort: 30030
            port: 3030
            targetPort: 3000
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: grafana
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      env: master
  template: 
    metadata: 
      labels: 
        env: master
      name: grafana-pod1
    spec: 
      containers: 
        - image: "sunny078/grafana:v1"
          name: graf-con
          volumeMounts: 
            - mountPath: /var/lib/grafana
              name: grafana
      volumes: 
        - name: grafana
          persistentVolumeClaim: 
            claimName: grafana-pvc



                                           
